import LAMBDA

def print_lambda(ahat,Qahat):
    # Method 1/a - ILS with 2 cands
    afixed,sqnorm,Ps,Qzhat,Z,nfixed,mu = LAMBDA.main(ahat,Qahat,1)
    print("--------------")
    print("Method 1/a - ILS with 2 integer candidates")
    print("--------------")
    print("\nVector of fixed integer ambiguities")
    print(afixed)
    print("\nVector of squared norms")
    print(sqnorm)
    print("\nAmbiguity success rate")
    print(Ps)
    print("\nVariance-covariance matrix of decorrelated ambiguities")
    print(Qzhat)
    print("\nZ-transformation matrix")
    print(Z)
    print("\nNumber of fixed ambiguities")
    print(nfixed)
    print("\nThreshold value of Ratio Test")
    print(mu)

    # Method 1/b - ILS with 3 cands
    afixed,sqnorm,Ps,Qzhat,Z,nfixed,mu = LAMBDA.main(ahat,Qahat,1,3)
    print("--------------")
    print("Method 1/b - ILS with 3 integer candidates")
    print("--------------")
    print("\nVector of fixed integer ambiguities")
    print(afixed)
    print("\nVector of squared norms")
    print(sqnorm)
    print("\nAmbiguity success rate")
    print(Ps)
    print("\nVariance-covariance matrix of decorrelated ambiguities")
    print(Qzhat)
    print("\nZ-transformation matrix")
    print(Z)
    print("\nNumber of fixed ambiguities")
    print(nfixed)
    print("\nThreshold value of Ratio Test")
    print(mu)

    # Method 2 - Integer rounding
    afixed,sqnorm,Ps,Qzhat,Z,nfixed,mu = LAMBDA.main(ahat,Qahat,2)
    print("--------------")
    print("Method 2 - IR")
    print("--------------")
    print("\nVector of fixed integer ambiguities")
    print(afixed)
    print("\nVector of squared norms")
    print(sqnorm)
    print("\nAmbiguity success rate")
    print(Ps)
    print("\nVariance-covariance matrix of decorrelated ambiguities")
    print(Qzhat)
    print("\nZ-transformation matrix")
    print(Z)
    print("\nNumber of fixed ambiguities")
    print(nfixed)
    print("\nThreshold value of Ratio Test")
    print(mu)

    # Method 3 - Integer bootstrapping
    afixed,sqnorm,Ps,Qzhat,Z,nfixed,mu = LAMBDA.main(ahat,Qahat,3)
    print("--------------")
    print("Method 3 - IB")
    print("--------------")
    print("\nVector of fixed integer ambiguities")
    print(afixed)
    print("\nVector of squared norms")
    print(sqnorm)
    print("\nAmbiguity success rate")
    print(Ps)
    print("\nVariance-covariance matrix of decorrelated ambiguities")
    print(Qzhat)
    print("\nZ-transformation matrix")
    print(Z)
    print("\nNumber of fixed ambiguities")
    print(nfixed)
    print("\nThreshold value of Ratio Test")
    print(mu)

    # Method 4/a - Partial ambiguity resolution with default P0=99.5%
    afixed,sqnorm,Ps,Qzhat,Z,nfixed,mu = LAMBDA.main(ahat,Qahat,4,2)
    print("--------------")
    print("Method 4/a - PAR using default P0")
    print("--------------")
    print("\nVector of fixed integer ambiguities")
    print(afixed)
    print("\nVector of squared norms")
    print(sqnorm)
    print("\nAmbiguity success rate")
    print(Ps)
    print("\nVariance-covariance matrix of decorrelated ambiguities")
    print(Qzhat)
    print("\nZ-transformation matrix")
    print(Z)
    print("\nNumber of fixed ambiguities")
    print(nfixed)
    print("\nThreshold value of Ratio Test")
    print(mu)

    # Method 4/b - Partial ambiguity resolution with P0=95%
    afixed,sqnorm,Ps,Qzhat,Z,nfixed,mu = LAMBDA.main(ahat,Qahat,4,2,0.950)
    print("--------------")
    print("Method 4/b - PAR with P0=95%")
    print("--------------")
    print("\nVector of fixed integer ambiguities")
    print(afixed)
    print("\nVector of squared norms")
    print(sqnorm)
    print("\nAmbiguity success rate")
    print(Ps)
    print("\nVariance-covariance matrix of decorrelated ambiguities")
    print(Qzhat)
    print("\nZ-transformation matrix")
    print(Z)
    print("\nNumber of fixed ambiguities")
    print(nfixed)
    print("\nThreshold value of Ratio Test")
    print(mu)

    # Method 5/a - ILS + FFRT with default P0=0.1%
    afixed,sqnorm,Ps,Qzhat,Z,nfixed,mu = LAMBDA.main(ahat,Qahat,5)
    print("-------------------")
    print("Method 5/a - ILS+FFRT with default P0=0.1%")
    print("-------------------")
    print("\nVector of fixed integer ambiguities")
    print(afixed)
    print("\nVector of squared norms")
    print(sqnorm)
    print("\nAmbiguity success rate")
    print(Ps)
    print("\nVariance-covariance matrix of decorrelated ambiguities")
    print(Qzhat)
    print("\nZ-transformation matrix")
    print(Z)
    print("\nNumber of fixed ambiguities")
    print(nfixed)
    print("\nThreshold value of Ratio Test")
    print(mu)

    # Method 5/b - ILS + FFRT with P0=1%
    afixed,sqnorm,Ps,Qzhat,Z,nfixed,mu = LAMBDA.main(ahat,Qahat,5,2,0.01)
    print("-------------------")
    print("Method 5/b - ILS+FFRT with P0=1%")
    print("-------------------")
    print("\nVector of fixed integer ambiguities")
    print(afixed)
    print("\nVector of squared norms")
    print(sqnorm)
    print("\nAmbiguity success rate")
    print(Ps)
    print("\nVariance-covariance matrix of decorrelated ambiguities")
    print(Qzhat)
    print("\nZ-transformation matrix")
    print(Z)
    print("\nNumber of fixed ambiguities")
    print(nfixed)
    print("\nThreshold value of Ratio Test")
    print(mu)